#JDBC Configutation for Database Connection
#jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://mysql-primary.mysql.svc.cluster.local:3306/accounts?useSSL=false&serverTimezone=UTC     
###jdbc:mysql://10.224.0.224:3306/accounts?useSSL=false&serverTimezone=UTC
jdbc.username=root
jdbc.password=Dexter@123

#Memcached Configuration For Active and StandBy Host
#For Active Host
memcached.active.host=10.100.87.175 
#memcached-0.memcached.svc.cluster.local            
###internal-a98f995539e2c41d6b58f6167a727067-667494108.us-east-2.elb.amazonaws.com
memcached.active.port=11211
#For StandBy Host
memcached.standBy.host=10.100.203.211
#memcached-1.memcached.svc.cluster.local         
###internal-a9f5232263def466db01760a8447bd86-159466975.us-east-2.elb.amazonaws.com
memcached.standBy.port=11211

#RabbitMq Configuration
rabbitmq.address=rabbitmq.rabbitmq.svc.cluster.local
#rabbitmq-0.rabbitmq-headless.rabbitmq.svc.cluster.local    
###internal-aeabba45c55794f4280f608199150390-1061532756.us-east-2.elb.amazonaws.com
rabbitmq.port=5672
rabbitmq.username=test
rabbitmq.password=test

